Truk = input("Masukkan Merk Truk Yang Kamu Punya :")
Plat = int(input("Masukkan Plat Truk Yang Kamu Punya :"))
Harga_Truk = float(input("Masukkan Harga Truk Kamu Yang Kamu Punya :"))
Warna_Truk = input("Masukkan Ya Warna Truk nya :")
Harga_Pajak = int(input("Masukkan Dulu Harga Pajaknya Baru Diproses ya :"))
list = []
list.insert(0,Truk)
list.insert(1,Plat)
list.insert(2,Harga_Truk)
list.insert(3,Warna_Truk)
list.insert(4,Harga_Pajak)
print(list[0])
print(list[1])
print(list[2])
print(list[3])
print(list[4])
print("Variabel Merk Truk          :", Truk, "Bertipe Data          :", type(Truk),     end="\n\n")
print("Variabel Plat Truk          :", Plat, "Bertipe Data          :", type(Plat),     end="\n\n")
print("Variabel harga Truk          :", Harga_Truk, "Bertipe Data          :", type(Harga_Truk),     end="\n\n")
print("Variabel warna Truk          :", Warna_Truk, "Bertipe Data          :", type(Warna_Truk),     end="\n\n")
print("Variabel harga pajak Truk          :", Harga_Pajak, "Bertipe Data          :", type(Harga_Pajak),     end="\n\n")